//created on: May 25, 2018
package com.rav.rules

//list any import classes here.
import com.rav.model.Restaurant;


//declare any global variables here
global com.rav.model.Result result;
global com.rav.model.Query q;


dialect "mvel"


rule "rate on city"
when
    r :  Restaurant( city == q.getCity()) 
then
	r.incrementRate();  
	r.justify("Is in " + r.getCity());
end

rule "rate on dine type"
when
    r : Restaurant( deliver  == q.getDeliver())
then
	r.incrementRate();    
	r.justify(r.getDineType())
end

rule "rate on has food"
when
    r : Restaurant( items.contains(q.getItemObj()))
then
	r.incrementRate();  
    r.justify("Has " + q.item);
end
